import '../models/track.dart';
import '../models/playlist.dart';

class MockData {

  static List<Track> get tracks => [
    Track(
      id: '1',
      title: 'Premier Gaou',
      artist: 'Magic System',
      album: 'Premier Gaou',
      coverUrl: '',
      duration: 245,
      genre: 'Zouglou',
      audioUrl: null,
    ),
    Track(
      id: '2',
      title: 'Bouger Bouger',
      artist: 'Magic System',
      album: 'Ki Dit Mie',
      coverUrl: '',
      duration: 212,
      genre: 'Zouglou',
      audioUrl: null,
    ),
    Track(
      id: '3',
      title: 'Kpangor',
      artist: 'DJ Arafat',
      album: 'Kpangor',
      coverUrl: '',
      duration: 198,
      genre: 'Coupe-Décalé',
      audioUrl: null,
    ),
    Track(
      id: '4',
      title: 'Dosabado',
      artist: 'DJ Arafat',
      album: 'Yorogang',
      coverUrl: '',
      duration: 225,
      genre: 'Coupe-Décalé',
      audioUrl: null,
    ),
    Track(
      id: '5',
      title: 'Coupé Décalé',
      artist: 'Douk Saga',
      album: 'Saga Africa',
      coverUrl: '',
      duration: 267,
      genre: 'Coupe-Décalé',
      audioUrl: null,
    ),
    Track(
      id: '6',
      title: "Ambiance à l'Africaine",
      artist: 'Meiway',
      album: 'Miss Lolo',
      coverUrl: '',
      duration: 310,
      genre: 'Zoblazo',
      audioUrl: null,
    ),
    Track(
      id: '7',
      title: 'Gnakpa Kessé',
      artist: 'Debordo Leekunfa',
      album: 'Spécialité',
      coverUrl: '',
      duration: 189,
      genre: 'Coupe-Décalé',
      audioUrl: null,
    ),
    Track(
      id: '8',
      title: 'Supporters',
      artist: 'Asalfo',
      album: 'Magic System',
      coverUrl: '',
      duration: 230,
      genre: 'Zouglou',
      audioUrl: null,
    ),
    Track(
      id: '9',
      title: 'Wôyô',
      artist: 'Serge Beynaud',
      album: 'Best Of',
      coverUrl: '',
      duration: 204,
      genre: 'Coupe-Décalé',
      audioUrl: null,
    ),
    Track(
      id: '10',
      title: 'Zoblazo',
      artist: 'Meiway',
      album: 'Zoblazo N°1',
      coverUrl: '',
      duration: 285,
      genre: 'Zoblazo',
      audioUrl: null,
    ),
    Track(
      id: '11',
      title: 'Tchin Tchin',
      artist: 'DJ Mix 1er',
      album: 'Hommage',
      coverUrl: '',
      duration: 196,
      genre: 'Coupe-Décalé',
      audioUrl: null,
    ),
    Track(
      id: '12',
      title: 'Anh ahn ahn',
      artist: 'Suspect 95',
      album: "Réécrire l'Histoire",
      coverUrl: '',
      duration: 178,
      genre: 'Rap Ivoire',
      audioUrl: null,
    ),
  ];

  static List<Playlist> get playlists => [
    Playlist(
      id: '1',
      name: 'Zouglou Hits',
      tracks: tracks.where((t) => ['1','2','8'].contains(t.id)).toList(),
    ),
    Playlist(
      id: '2',
      name: 'Coupe-Décalé Fire',
      tracks: tracks.where((t) => ['3','4','5','7','9','11'].contains(t.id)).toList(),
    ),
    Playlist(
      id: '3',
      name: 'Best of CI',
      tracks: tracks.where((t) => ['1','3','5','6','9','10','12'].contains(t.id)).toList(),
    ),
    Playlist(
      id: '4',
      name: 'Ambiance Maquis',
      tracks: tracks.where((t) => ['2','4','6','8','10'].contains(t.id)).toList(),
    ),
  ];
}